#WEB环境后台域名配置
#测试站后台
test:
  url: http://www.alafei.com/#/home



#API环境配置

#登录账号密码
username: 12133446101
password: 123456

#测试环境api地址
API_URL: http://api.test.by-998.com/

#开发环境api地址
#API_URL: http://api.by-998.com/

#正式环境api地址
#API_URL: http://api.ky9997.com/

#HY电玩城环境api地址
#API_URL: https://api.hydw99.com/

#95棋牌环境api地址
#API_URL: http://api.909595.com/

#正式环境新api地址
#API_URL: api.xmgames.bytechcdn.com/



#公共配置

#日志
log:
  file_name:
  backup: 5
  console_level: INFO
  file_level: DEBUG
  pattern:


#数据库
#测试站
db:
  host: 47.91.245.176
  port: 3306
  user: kyqpt
  passwd: ANrE7spwTFXZGTtH
  db: kyqpt

